// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

var AModel, Joi, User;
Joi = require('joi');
AModel = require('../../lib/amodel');

module.exports = User = (function(superClass) {
  extend(User, superClass);

  User.schema = {
    id: Joi.string().regex(/^[0-9a-fA-F]{24}$/),
    name: Joi.string().min(3).max(100),
    hash: Joi.string().length(44),
    age: Joi.number().min(10).max(200),
    mail: Joi.string().email(),
  };

  function User(attrs) {
    User.__super__.constructor.call(this, attrs, User.schema);
  }

  User.prototype.userify = function() {
    var i, k, len, ref, ret;
    ret = {};
    ref = ['deck_id', 'decks', 'armies', 'map_id'];
    for (i = 0, len = ref.length; i < len; i++) {
      k = ref[i];
      ret[k] = this.attrs[k];
    }
    ret.gold = this.attrs.cash;
    ret.decks = JSON.parse(ret.decks);
    return ret;
  };

  User.prototype.playerify = function() {
    var decks;
    decks = JSON.parse(this.attrs.decks);
    return {
      id: this.attrs.id,
      deck: decks[this.attrs.deck_id]
    };
  };

  return User;

})(AModel);
